language: objective-c
before_install:
  - brew update
  - brew --env
  - brew config
install:
  - mkdir -p $(brew --repo)/Library/Taps/shemerey
  - ln -s $PWD $(brew --repo)/Library/Taps/shemerey/homebrew-neovim-dot-app
  - brew tap --repair
  - brew tap
  - export PATH="$PWD/bin:${PATH}"
script:
  - brew install neovim-dot-app --HEAD --verbose
  - brew head-audit neovim-dot-app --strict
matrix:
  fast_finish: true
